# Generated by Django 4.2.5 on 2023-09-30 02:16

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=product.models.defult_create_date),
        ),
        migrations.AddField(
            model_name='product',
            name='update_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='update_date',
            field=models.DateField(null=True),
        ),
    ]
