# Generated by Django 4.2.5 on 2023-09-30 14:54

import company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_description', models.CharField(max_length=500)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(max_length=200, null=True)),
                ('adress_line3', models.CharField(max_length=200, null=True)),
                ('mobile_no1', models.CharField(max_length=12)),
                ('mobile_no2', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=company.models.defult_create_date)),
                ('created_by', models.IntegerField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.IntegerField(null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
