# Generated by Django 4.2.5 on 2023-09-30 15:14

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='created_date',
            field=models.DateTimeField(default=company.models.defult_create_date),
        ),
    ]
